name: build-sphinx-to-gh-pages

on:
  push:
    branches:
      - master

jobs:
  build_sphinx:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./docs_"

    - name: Commit documentation changes
      run: |
        git clone https://github.com/hyoo/Candle.git --branch gh-pages --single-branch gh-pages
        cp -r ../docs/html/* gh-pages/
        cp .nojekyll gh-pages/
        cp index.html gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }} 
